### Start new Kalah game
POST {{url}}/kalah/games
Content-Type: application/json
Authorization: Basic adam@bol.com 1234

{
  "playerIds": [
    1,
    2
  ]
}

### Get Kalah game
GET {{url}}/kalah/games/1
Authorization: Basic bob@bol.com 4321

### Adam makes a turn
POST {{url}}/kalah/games/1/moves
Content-Type: application/json
Authorization: Basic adam@bol.com 1234

{
  "pitIndex": 0
}

### Bob makes a turn
POST {{url}}/kalah/games/1/moves
Content-Type: application/json
Authorization: Basic bob@bol.com 4321

{
  "pitIndex": 1
}
