### Create Player Adam
POST {{url}}/players
Content-Type: application/json

{
  "email": "adam@bol.com",
  "nickname": "Adam",
  "password": "1234"
}

### Create Player Bob
POST {{url}}/players
Content-Type: application/json

{
  "email": "bob@bol.com",
  "nickname": "Bob",
  "password": "qwerty"
}
